# Site settings
title: My Projects
author:
name: Ali Samir
email: ali.samir.elsaid@gmail.com
description: "A webpage for All my projects and accomplishments."

# Build settings
remote_theme: jekyll/minima
